# Loonå…¨å±€é…ç½®æ–‡ä»¶
# Mr.Kong Update By 2020-07-26
# Github Address(https://github.com/FocusProgram/proxy-conf.git)
# GitHubä¸»é¡µ(https://github.com/nzw9314)
# TGé€šçŸ¥é¢‘é“ (https://t.me/nzw9314News)

[General]
ipv6 = false
skip-proxy = 10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,192.0.2.0/24,192.168.0.0/16,198.51.100.0/24,224.0.0.0/4,*.local,localhostlocal
bypass-tun = 10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,192.0.2.0/24,192.168.0.0/16,198.51.100.0/24,224.0.0.0/4
# [DNS] => DNS æœåŠ¡å™¨
dns-server = system,1.2.4.8,119.29.29.29,223.5.5.5
allow-udp-proxy = true
host = 127.0.0.1

[Remote Proxy]
# è®¢é˜…èŠ‚ç‚¹
# åˆ«å = è®¢é˜…URL
âœˆï¸suying = https://example/server-complete.txt
âœˆï¸suying = https://example/server-complete.txt
âœˆholytech = https://example/server-complete.txt

[Remote Filter]
# ç­›é€‰è®¢é˜…èŠ‚ç‚¹ï¼Œç­›é€‰åçš„ç»“æœå¯åŠ å…¥åˆ°ç­–ç•¥ç»„ä¸­ï¼Œç›®å‰æ”¯æŒä¸‰ç§ç­›é€‰æ–¹å¼
# NodeSelect: ä½¿ç”¨åœ¨UIä¸Šé€‰æ‹©çš„èŠ‚ç‚¹ã€‚
# NameKeyword: æ ¹æ®æä¾›çš„å…³é”®è¯å¯¹è®¢é˜…ä¸­æ‰€æœ‰èŠ‚ç‚¹çš„åç§°è¿›è¡Œç­›é€‰ï¼Œä½¿ç”¨ç­›é€‰åçš„èŠ‚ç‚¹ã€‚
# NameRegex: æ ¹æ®æä¾›çš„æ­£åˆ™è¡¨è¾¾å¼å¯¹è®¢é˜…ä¸­æ‰€æœ‰èŠ‚ç‚¹çš„åç§°è¿›è¡Œç­›é€‰ï¼Œä½¿ç”¨ç­›é€‰åçš„èŠ‚ç‚¹ã€‚
ğğšğ²ğğšğ¥ = NodeSelect,âœˆï¸suying,âœˆï¸holytech
ğğğ­ğŸğ¥ğ¢ğ± = NameKeyword,âœˆï¸suying,âœˆï¸holytech, FilterKey = Netflix
ğŸ‡­ğŸ‡°é¦™æ¸¯ = NameRegex,âœˆï¸suying,âœˆï¸holytech, FilterKey = é¦™æ¸¯|HK
ğŸ‡¯ğŸ‡µæ—¥æœ¬ = NameRegex,âœˆï¸suying,âœˆï¸holytech, FilterKey = æ—¥æœ¬|JP
ğŸ‡°ğŸ‡·éŸ©å›½ = NameRegex,âœˆï¸suying,âœˆï¸holytech, FilterKey = éŸ©å›½|KR
ğŸ‡ºğŸ‡¸ç¾å›½ = NameRegex,âœˆï¸suying,âœˆï¸holytech, FilterKey = ç¾å›½|US
Other = NameRegex,âœˆï¸suying,âœˆï¸holytech, FilterKey = ^(?!.*(HK|JP|US|KR|é¦™æ¸¯|æ—¥æœ¬|éŸ©å›½|ç¾å›½)).*$

[Proxy]
# æœ¬åœ°èŠ‚ç‚¹

# å†…ç½® DIRECTã€REJECT ç­–ç•¥

# èŠ‚ç‚¹åç§° = åè®®ï¼ŒæœåŠ¡å™¨åœ°å€ï¼ŒæœåŠ¡å™¨ç«¯å£ï¼ŒåŠ å¯†åè®®ï¼Œå¯†ç ï¼Œ
1 = Shadowsocks,1.2.3.4,443,aes-128-gcm,"â€passwordâ€œ"
2 = Shadowsocks,1.2.3.4,443,aes-128-gcm,"â€passwordâ€œ"
3 = ShadowsocksR,1.2.3.4,443,aes-256-cfb,"â€passwordâ€œ",auth_aes128_md5,{},tls1.2_ticket_auth,{}
4 = ShadowsocksR,1.2.3.4,10076,aes-128-cfb,"â€passwordâ€œ",auth_aes128_md5,{},tls1.2_ticket_auth,{}
# vmess
# èŠ‚ç‚¹åç§° = åè®®ï¼ŒæœåŠ¡å™¨åœ°å€ï¼Œç«¯å£ï¼ŒåŠ å¯†æ–¹å¼ï¼ŒUUIDï¼Œä¼ è¾“æ–¹å¼:(tcp/ws),pathï¼šwebsocketæ¡æ‰‹headerä¸­çš„pathï¼Œhostï¼šwebsocketæ¡æ‰‹headerä¸­çš„pathï¼Œover-tls:æ˜¯å¦tlsï¼Œtls-nameï¼šè¿œç«¯wæœåŠ¡å™¨åŸŸåï¼Œskip-cert-verifyï¼šæ˜¯å¦è·³è¿‡è¯ä¹¦æ ¡éªŒï¼ˆé»˜è®¤å¦ï¼‰
#5 = vmess, 1.2.3.4, 10086, aes-128-gcm,â€uuidâ€œ,transport:ws,path:/,host:icloud.com,over-tls:true,tls-name:youtTlsServerName.com,skip-cert-verify:false

# è§£é”ç½‘æ˜“äº‘éŸ³ä¹ç°è‰²æ­Œæ›²
ğŸ§ = http,106.52.127.72,19951

[Proxy Group]
# ç­–ç•¥ç»„

# èŠ‚ç‚¹é€‰é¡¹
ğŸ•¹ğ…ğ¢ğ§ğšğ¥ = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ”°ğğ«ğ¨ğ±ğ² = select,â™»ï¸ğ€ğ®ğ­ğ¨,ğŸŒ€ğ’ğğ¥ğğœğ­,ğŸ”´ğ…ğšğ¥ğ¥ğ›ğšğœğ¤

# url-testæ¨¡å¼ï¼Œç»™æä¾›çš„urlå‘å‡ºhttp headerè¯·æ±‚ï¼Œæ ¹æ®è¿”å›ç»“æœï¼Œé€‰æ‹©æµ‹é€Ÿæœ€å¿«çš„èŠ‚ç‚¹ï¼Œé»˜è®¤é—´éš”600sï¼Œæµ‹é€Ÿè¶…æ—¶æ—¶é—´5sï¼Œä¸ºäº†é¿å…èµ„æºæµªè´¹ï¼Œå»ºè®®èŠ‚ç‚¹æ•°ä¸è¦è¿‡å¤šï¼Œåªæ”¯æŒå•ä¸ªèŠ‚ç‚¹å’Œè¿œç«¯èŠ‚ç‚¹ï¼Œå…¶ä»–ä¼šè¢«å¿½ç•¥
â™»ï¸ğ€ğ®ğ­ğ¨ = url-test,ğŸ‡­ğŸ‡°é¦™æ¸¯,ğŸ‡¯ğŸ‡µæ—¥æœ¬,ğŸ‡°ğŸ‡·éŸ©å›½,ğŸ‡ºğŸ‡¸ç¾å›½,url = http://bing.com/,interval = 600

# selectæ¨¡å¼,æ‰‹åŠ¨é€‰æ‹©æ¨¡å¼
ğŸŒ€ğ’ğğ¥ğğœğ­ = select,ğŸ‡­ğŸ‡°é¦™æ¸¯,ğŸ‡¯ğŸ‡µæ—¥æœ¬,ğŸ‡°ğŸ‡·éŸ©å›½,ğŸ‡ºğŸ‡¸ç¾å›½

# fallbackæ¨¡å¼ï¼Œå’Œurl-testç±»ä¼¼ï¼Œä¸åŒçš„æ˜¯ä¼šæ ¹æ®é¡ºåºè¿”å›ç¬¬ä¸€ä¸ªå¯ç”¨çš„èŠ‚ç‚¹ï¼Œä¸ºäº†é¿å…èµ„æºæµªè´¹ï¼Œå»ºè®®èŠ‚ç‚¹æ•°ä¸è¦è¿‡å¤šï¼Œåªæ”¯æŒå•ä¸ªèŠ‚ç‚¹å’Œè¿œç«¯èŠ‚ç‚¹ï¼Œå…¶ä»–ä¼šè¢«å¿½ç•¥
ğŸ”´ğ…ğšğ¥ğ¥ğ›ğšğœğ¤ = fallback,ğŸ‡­ğŸ‡°é¦™æ¸¯,ğŸ‡¯ğŸ‡µæ—¥æœ¬,ğŸ‡°ğŸ‡·éŸ©å›½,ğŸ‡ºğŸ‡¸ç¾å›½,REJECT,url = http://bing.com/,interval = 600

ğŸµğ“ğ¢ğ¤ğ“ğ¨ğ¤ = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ–¥ğğğ­ğŸğ¥ğ¢ğ± = select,ğğğ­ğŸğ¥ğ¢ğ±,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ’³ğğšğ²ğğšğ¥ = select,ğğšğ²ğğšğ¥,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ“±ğ“ğğ¥ğğ ğ«ğšğ¦ = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ¬ğ˜ğ¨ğ®ğ“ğ®ğ›ğ = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­
ğŸ”ğğ¨ğ«ğ§ğ‡ğ®ğ› = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­

# ğŸ”“ç½‘æ˜“äº‘éŸ³ä¹ç°è‰²æ­Œæ›²,éœ€è¦èŠ‚ç‚¹æ”¯æŒè§£é”
ğŸ§ğğğ­ğğšğ¬ğğŒğ®ğ¬ğ¢ğœ = select,ğŸ¯ğƒğ¢ğ«ğğœğ­,ğŸ§,ğŸ”°ğğ«ğ¨ğ±ğ²

# ç½‘ç»œæµ‹é€Ÿ
ğŸš€ğ’ğ©ğğğğ“ğğ¬ğ­ = select,ğŸ”°ğğ«ğ¨ğ±ğ²,ğŸ¯ğƒğ¢ğ«ğğœğ­

# è‹¹æœæœåŠ¡
ğŸğ€ğ©ğ©ğ¥ğ = select,ğŸ¯ğƒğ¢ğ«ğğœğ­,ğŸ”°ğğ«ğ¨ğ±ğ²

# ç™½åå•æ¨¡å¼ PROXYï¼Œé»‘åå•æ¨¡å¼ DIRECT

# å¹¿å‘Šæ‹¦æˆª
ğŸš«ğ€ğ ğğ¥ğ¨ğœğ¤ = select,â›”ï¸ğ‘ğğ£ğğœğ­,ğŸ¯ğƒğ¢ğ«ğğœğ­

# ç›´æ¥è¿æ¥
ğŸ¯ğƒğ¢ğ«ğğœğ­ = select,DIRECT

# æ‹¦æˆª
â›”ï¸ğ‘ğğ£ğğœğ­ = select,REJECT

# SSID
# åˆ«å = ssidï¼Œé»˜è®¤ = ç­–ç•¥ï¼Œ èœ‚çª = ç­–ç•¥ï¼Œ ssidåç§° = ç­–ç•¥
#SSID = ssid, default = PROXY, cellular = DIRECT, â€DivineEngineâ€œ = PROXY

[Rule]
# æœ¬åœ°è§„åˆ™
# Type:DOMAIN-SUFFIX,DOMAIN,DOMAIN-KEYWORD,USER-AGENT,URL-REGEX,IP-CIDR
# Strategy:DIRECT,Proxy,REJECT
# Options:force-remote-dns(Default:false),no-resolve

#  ğğğ­ğğšğ¬ğğŒğ®ğ¬ğ¢ğœ
DOMAIN-SUFFIX,music.126.net,DIRECT

# GeoIP China
GEOIP,CN,ğŸ¯ğƒğ¢ğ«ğğœğ­
FINAL, ğŸ•¹ğ…ğ¢ğ§ğšğ¥

[Remote Rule]

# è®¢é˜…è§„åˆ™
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Liby.list,ğŸš«ğ€ğ ğğ¥ğ¨ğœğ¤
# BlockOTA
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/BlockOTA.list,ğŸš«ğ€ğ ğğ¥ğ¨ğœğ¤
# Antirevoke
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/Antirevoke.list,ğŸš«ğ€ğ ğğ¥ğ¨ğœğ¤
# > TikTok
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/TikTok.list,ğŸµğ“ğ¢ğ¤ğ“ğ¨ğ¤
# > Youtube
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/YouTube.list,ğŸ¬ğ˜ğ¨ğ®ğ“ğ®ğ›ğ
# > Netflix
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/Netflix.list,ğŸ–¥ğğğ­ğŸğ¥ğ¢ğ±
# > PronHub
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/Pornhub.list,ğŸ”ğğ¨ğ«ğ§ğ‡ğ®ğ›
# Telegram
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/Telegram.list,ğŸ“±ğ“ğğ¥ğğ ğ«ğšğ¦
# > PayPal
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/PayPal.list,ğŸ’³ğğšğ²ğğšğ¥
# > Outlookã€Gmail
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/Mail.list,ğŸ”°ğğ«ğ¨ğ±ğ²
# > GoogleDrive
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/GoogleDrive.list,ğŸ”°ğğ«ğ¨ğ±ğ²
# Speedtest
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Sub/Speedtest.list,ğŸš€ğ’ğ©ğğğğ“ğğ¬ğ­

# >Unlock NeteaseMusic
https://raw.githubusercontent.com/nzw9314/Surge/master/Ruleset/UnlockNeteaseMusic.list,ğŸ§ğğğ­ğğšğ¬ğğŒğ®ğ¬ğ¢ğœ

https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Apple_CDN.list,ğŸğ€ğ©ğ©ğ¥ğ
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Apple_API.list,ğŸğ€ğ©ğ©ğ¥ğ

https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/AsianMedia.list,ğŸ¯ğƒğ¢ğ«ğğœğ­
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/GlobalMedia.list,ğŸ”°ğğ«ğ¨ğ±ğ²

https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Domestic.list,ğŸ¯ğƒğ¢ğ«ğğœğ­
https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Global.list,ğŸ”°ğğ«ğ¨ğ±ğ²

[URL Rewrite]
# æœ¬åœ°é‡å†™

# > TikTok Unlock (By Choler)
# åŒºåŸŸè¯·ä¿®æ”¹ä¸‹æ–¹å›½å®¶ä»£ç ï¼Œé»˜è®¤ä¸ºæ—¥æœ¬ JP
# AF - Afghanistan é˜¿å¯Œæ±—
# AL - Albania é˜¿å°”å·´å°¼äºš
# DZ - Algeria é˜¿å°”åŠåˆ©äºš
# AS - American Samoa ä¸œè¨æ‘©äºš
# AD - Andorra å®‰é“å°”
# AO - Angola å®‰å“¥æ‹‰
# Av - Anguilla å®‰åœ­æ‹‰å²›
# AQ - Antarctica å—ææ´²
# AG - Antigua and Barbuda å®‰æç“œå’Œå·´å¸ƒè¾¾
# AR - Argentina é˜¿æ ¹å»·
# AM - Armenia äºšç¾å°¼äºš
# AA - Aruba é˜¿é²å·´
# AU - Australia æ¾³å¤§åˆ©äºš
# AT - Austria å¥¥åœ°åˆ©
# AZ - Azerbaijan é˜¿å¡æ‹œç–†
# BF - Bahamas å·´å“ˆé©¬
# BH - Bahrain å·´æ—
# BB - Barbados å·´å·´å¤šæ–¯
# BD - Bangladesh å­ŸåŠ æ‹‰
# BY - Belarus ç™½ä¿„ç½—æ–¯
# BE - Belgium æ¯”åˆ©æ—¶
# BZ - Belize ä¼¯é‡Œå…¹
# BJ - Benin è´å®
# BM - Bermuda ç™¾æ…•å¤§
# BS - Bahamas å·´å“ˆé©¬
# BT - Bhutan ä¸ä¸¹
# BW - Botswana åšèŒ¨ç“¦çº³
# BO - Bolivia ç»åˆ©ç»´äºš
# BA - Bosnia and Herzegovina æ³¢é»‘
# BV - Bouvet Island å¸ƒéŸ¦å²›
# BR - Brazil å·´è¥¿
# IO - British Indian Ocean Territory è‹±å±å°åº¦æ´‹é¢†åœ°
# BN - Brunei Darussalam æ–‡è±å¸ƒé²è¨å…°
# BG - Bulgaria ä¿åŠ åˆ©äºš
# BF - Burkina Faso å¸ƒåŸºçº³æ³•ç´¢
# BI - Burundi å¸ƒéš†è¿ª
# KH - Cambodia (Internet) æŸ¬åŸ”å¯¨
# CB - Cambodia (CIA World Fact Book) æŸ¬åŸ”å¯¨
# CM - Cameroon å–€éº¦éš†
# CA - Canada åŠ æ‹¿å¤§
# CV - Cape Verde ä½›å¾—è§’
# KY - Cayman Islands å¼€æ›¼ç¾¤å²›
# CF - Central African Republic ä¸­é
# TD - Chad ä¹å¾—
# CL - Chile æ™ºåˆ©
# CN - China ä¸­å›½
# CX - Christmas Island åœ£è¯å²›
# CC - Cocos (Keeling) Islands å¯å¯æ–¯ç¾¤å²›
# CO - Colombia å“¥ä¼¦æ¯”äºš
# KM - Comoros ç§‘æ‘©ç½—
# CG - Congo åˆšæœ
# CD - Congo, Democratic Republic åˆšæœ
# CK - Cook Islands åº“å…‹ç¾¤å²›
# CR - Costa Rica å“¥æ–¯è¾¾é»åŠ 
# CI - Cote DIvoire (Ivory Coast) è±¡ç‰™æµ·å²¸
# HR - Croatia (Hrvatska) å…‹ç½—åœ°äºš
# CU - Cuba å¤å·´
# CY - Cyprus å¡æ™®è·¯æ–¯
# CZ - Czech Republic æ·å…‹
# CS - Czechoslovakia (former) æ·å…‹æ–¯æ´›ä¼å…‹
# DK - Denmark ä¸¹éº¦
# DJ - Djibouti å‰å¸ƒæ
# DM - Dominica å¤šç±³å°¼åŠ å…±å’Œå›½
# DO - Dominican Republic å¤šç±³å°¼åŠ è”é‚¦
# TP - East Timor ä¸œå¸æ±¶
# EC - Ecuador å„ç“œå¤šå°”
# EG - Egypt åŸƒåŠ
# SV - El Salvador è¨å°”ç“¦å¤š
# GQ - Equatorial Guinea èµ¤é“å‡ å†…äºš
# ER - Eritrea
# EE - Estonia çˆ±æ²™å°¼äºš
# ET - Ethiopia åŸƒå¡ä¿„æ¯”äºš
# FK - Falkland Islands (Malvinas) ç¦å…°å…‹ç¾¤å²›
# FO - Faroe Islands æ³•ç½—ç¾¤å²›
# FJ - Fiji æ–æµ
# FI - Finland èŠ¬å…°
# FR - France æ³•å›½
# FX - France, Metropolitan
# GF - French Guiana æ³•å±åœ­äºšé‚£
# PF - French Polynesia æ³•å±ç»é‡Œå°¼è¥¿äºš
# TF - French Southern Territories æ³•å›½å—éƒ¨é¢†åœ°
# MK - F.Y.R.O.M. (Macedonia)
# GA - Gabon åŠ è“¬
# GM - Gambia å†ˆæ¯”äºš
# GE - Georgia æ ¼é²å‰äºš
# DE - Germany å¾·å›½
# GH - Ghana åŠ çº³
# GI - Gibraltar ç›´å¸ƒç½—é™€
# GB - Great Britain (UK) è‹±å›½
# GR - Greece å¸Œè…Š
# GL - Greenland æ ¼é™µå…°å²›
# GD - Grenada æ ¼æ—çº³è¾¾
# GP - Guadeloupe æ³•å±å¾·æ´›æ™®ç¾¤å²›
# GU - Guam å…³å²›
# GT - Guatemala å±åœ°é©¬æ‹‰
# GN - Guinea å‡ å†…äºš
# GW - Guinea-Bissau å‡ å†…äºšæ¯”ç»
# GY - Guyana åœ­äºšé‚£
# HT - Haiti æµ·åœ°
# HM - Heard and McDonald Islands èµ«å¾·å’Œéº¦å…‹å”çº³ç¾¤å²›
# HN - Honduras æ´ªéƒ½æ‹‰æ–¯
# HK - Hong Kong ä¸­å›½é¦™æ¸¯ç‰¹åŒº
# HU - Hungary åŒˆç‰™åˆ©
# IS - Iceland å†°å²›
# IN - India å°åº¦
# ID - Indonesia å°åº¦å°¼è¥¿äºš
# IR - Iran ä¼Šæœ—
# IQ - Iraq ä¼Šæ‹‰å…‹
# IE - Ireland çˆ±å°”å…°
# IL - Israel ä»¥è‰²åˆ—
# IT - Italy æ„å¤§åˆ©
# JM - Jamaica ç‰™ä¹°åŠ 
# JP - Japan æ—¥æœ¬
# JO - Jordan çº¦æ—¦
# KZ - Kazakhstan å“ˆè¨å…‹æ–¯å¦
# KE - Kenya è‚¯å°¼äºš
# KI - Kiribati åŸºé‡Œå·´æ–¯
# KP - Korea (North) éŸ©å›½
# KR - Korea (South) æœé²œ
# KW - Kuwait ç§‘å¨ç‰¹
# KG - Kyrgyzstan å‰å°”å‰æ–¯æ–¯å¦
# LA - Laos è€æŒ
# LV - Latvia æ‹‰æ‰˜ç»´äºš
# LB - Lebanon é»å·´å«©
# LI - Liechtenstein åˆ—æ”¯é¡¿å£«ç™»
# LR - Liberia åˆ©æ¯”é‡Œäºš
# LY - Libya åˆ©æ¯”äºš
# LS - Lesotho è±ç´¢æ‰˜
# LT - Lithuania ç«‹é™¶å®›
# LU - Luxembourg å¢æ£®å ¡
# MO - Macau ä¸­å›½æ¾³é—¨ç‰¹åŒº
# MG - Madagascar é©¬è¾¾åŠ æ–¯åŠ 
# MW - Malawi é©¬æ‹‰ç»´
# MY - Malaysia é©¬æ¥è¥¿äºš
# MV - Maldives é©¬å°”ä»£å¤«
# ML - Mali é©¬é‡Œ
# MT - Malta é©¬è€³ä»–
# MH - Marshall Islands é©¬ç»å°”ç¾¤å²›
# MQ - Martinique æ³•å±é©¬æå°¼å…‹ç¾¤å²›
# MR - Mauritania æ¯›é‡Œå¡”å°¼äºš
# MU - Mauritius æ¯›é‡Œæ±‚æ–¯
# YT - Mayotte
# MX - Mexico å¢¨è¥¿å“¥
# FM - Micronesia ç±³å…‹ç½—å°¼è¥¿äºš
# MC - Monaco æ‘©çº³å“¥
# MD - Moldova æ‘©å°”å¤šç“¦
# MA - Morocco æ‘©æ´›å“¥
# MN - Mongolia è’™å¤
# MS - Montserrat è’™å¡æ‹‰ç‰¹å²›
# MZ - Mozambique è«æ¡‘æ¯”å…‹
# MM - Myanmar ç¼…ç”¸
# NA - Namibia çº³ç±³æ¯”äºš
# NR - Nauru ç‘™é²
# NP - Nepal å°¼æ³Šå°”
# NL - Netherlands è·å…°
# AN - Netherlands Antilles è·å±å®‰å¾·åˆ—æ–¯
# NT - Neutral Zone ä¸­ç«‹åŒºï¼ˆæ²™ç‰¹-ä¼Šæ‹‰å…‹é—´ï¼‰
# NC - New Caledonia æ–°å¡é‡Œå¤šå°¼äºš
# NZ - New Zealand (Aotearoa) æ–°è¥¿å…°
# NI - Nicaragua å°¼åŠ æ‹‰ç“œ
# NE - Niger å°¼æ—¥å°”
# NG - Nigeria å°¼æ—¥åˆ©äºš
# NU - Niue çº½çˆ±
# NF - Norfolk Island è¯ºç¦å…‹å²›
# MP - Northern Mariana Islands åŒ—é©¬é‡Œäºšçº³ç¾¤å²›
# NO - Norway æŒªå¨
# OM - Oman é˜¿æ›¼
# PK - Pakistan å·´åŸºæ–¯å¦
# PW - Palau å¸•åŠ³
# PA - Panama å·´æ‹¿é©¬
# PG - Papua New Guinea å·´å¸ƒäºšæ–°å‡ å†…äºš
# PY - Paraguay å·´æ‹‰åœ­
# PE - Peru ç§˜é²
# PH - Philippines è²å¾‹å®¾
# PN - Pitcairn çš®ç‰¹å…‹æ©å²›
# PL - Poland æ³¢å…°
# PT - Portugal è‘¡è„ç‰™
# PR - Puerto Rico æ³¢å¤šé»å„
# QA - Qatar å¡å¡”å°”
# RE - Reunion æ³•å±å°¼ç•™æ—ºå²›
# RO - Romania ç½—é©¬å°¼äºš
# RU - Russian Federation ä¿„ç½—æ–¯
# RW - Rwanda å¢æ—ºè¾¾
# GS - S. Georgia and S. Sandwich Isls.
# KN - Saint Kitts and Nevis åœ£åŸºèŒ¨å’Œå°¼ç»´æ–¯
# LC - Saint Lucia åœ£å¢è¥¿äºš
# VC - Saint Vincent and the Grenadines åœ£æ–‡æ£®ç‰¹å’Œæ ¼é™µçº³ä¸æ–¯
# WS - Samoa è¥¿è¨æ‘©äºš
# SM - San Marino åœ£é©¬åŠ›è¯º
# ST - Sao Tome and Principe åœ£å¤šç¾å’Œæ™®æ—è¥¿æ¯”
# SA - Saudi Arabia æ²™ç‰¹é˜¿æ‹‰ä¼¯
# SN - Senegal å¡å†…åŠ å°”
# SC - Seychelles å¡èˆŒå°”
# SL - Sierra Leone å¡æ‹‰åˆ©æ˜‚
# SG - Singapore æ–°åŠ å¡
# SI - Slovenia æ–¯ç½—æ–‡å°¼äºš
# SK - Slovak Republic æ–¯æ´›ä¼å…‹
# Sb - Solomon Islands æ‰€ç½—é—¨ç¾¤å²›
# SO - Somalia ç´¢é©¬é‡Œ
# ZA - South Africa å—é
# ES - Spain è¥¿ç­ç‰™
# LK - Sri Lanka æ–¯é‡Œå…°å¡
# SH - St. Helena
# PM - St. Pierre and Miquelon åœ£çš®è‰¾å°”å’Œå¯†å…‹éš†ç¾¤å²›
# SD - Sudan è‹ä¸¹
# SR - Suriname è‹é‡Œå—
# SJ - Svalbard and Jan Mayen Islands æ–¯ç“¦å°”å·´ç‰¹å’Œæ‰¬é©¬å»¶å²›
# SZ - Swaziland æ–¯å¨å£«å…°
# SE - Sweden ç‘å…¸
# CH - Switzerland ç‘å£«
# SY - Syria å™åˆ©äºš
# TW - Taiwan ä¸­å›½å°æ¹¾çœ
# TJ - Tajikistan å¡”å‰å…‹æ–¯å¦
# TZ - Tanzania å¦æ¡‘å°¼äºš
# TH - Thailand æ³°å›½
# TG - Togo å¤šå“¥
# TK - Tokelau æ‰˜å…‹åŠ³ç¾¤å²›
# TO - Tonga æ±¤åŠ 
# TT - Trinidad and Tobago ç‰¹ç«‹å°¼è¾¾å’Œå¤šå·´å“¥
# TN - Tunisia çªå°¼æ–¯
# TR - Turkey åœŸå°”å…¶
# TM - Turkmenistan åœŸåº“æ›¼æ–¯å¦
# TC - Turks and Caicos Islands ç‰¹å…‹æ–¯å’Œå‡¯ç§‘æ–¯ç¾¤å²›
# TV - Tuvalu å›¾ç“¦å¢
# UG - Uganda ä¹Œå¹²è¾¾
# UA - Ukraine ä¹Œå…‹å…°
# AE - United Arab Emirates é˜¿è”é…‹
# UK - United Kingdom è‹±å›½
# US - United States ç¾å›½
# UM - US Minor Outlying Islands ç¾å›½æµ·å¤–é¢†åœ°
# UY - Uruguay ä¹Œæ‹‰åœ­
# SU - USSR (former) å‰è‹è”
# UZ - Uzbekistan ä¹Œå…¹åˆ«å…‹æ–¯å¦
# VU - Vanuatu ç“¦åŠªé˜¿é²
# VA - Vatican City State (Holy See) æ¢µè’‚å²—
# VE - Venezuela å§”å†…ç‘æ‹‰
# VN - Viet Nam è¶Šå—
# VG - Virgin Islands (British) è‹±å±ç»´äº¬ç¾¤å²›
# VI - Virgin Islands (U.S.) ç¾å±ç»´äº¬ç¾¤å²›
# WF - Wallis and Futuna Islands ç“¦é‡Œæ–¯å’Œç¦å›¾çº³ç¾¤å²›
# EH - Western Sahara è¥¿æ’’å“ˆæ‹‰
# YE - Yemen ä¹Ÿé—¨
# YU - Yugoslavia å—æ–¯æ‹‰å¤«
# ZM - Zambia èµæ¯”äºš
# (ZR - Zaire) - See CD Congo, Democratic Republic æ‰ä¼Šå°”
# ZW - Zimbabwe æ´¥å·´å¸ƒéŸ¦
(?<=_region=)CN(?=&) JP 307
(?<=&app_version=)16..(?=.?.?&) 1 307
(?<=\?version_code=)16..(?=.?.?&) 1 307

# > æŠ–éŸ³ å»å¹¿å‘Š&æ°´å°
# éœ€é…åˆè„šæœ¬ä½¿ç”¨
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/feed\/ https://aweme.snssdk.com/aweme/v1/feed/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/aweme\/post\/ https://aweme.snssdk.com/aweme/v1/aweme/post/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/follow\/feed\/ https://aweme.snssdk.com/aweme/v1/follow/feed/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/nearby\/feed\/ https://aweme.snssdk.com/aweme/v1/nearby/feed/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/search\/item\/ https://aweme.snssdk.com/aweme/v1/search/item/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/general\/search\/single\/ https://aweme.snssdk.com/aweme/v1/general/search/single/ header
^https?:\/\/[\w-]+\.amemv\.com\/aweme\/v\d\/hot/search\/video\/list\/ https://aweme.snssdk.com/aweme/v1/hot/search/video/list/ header

enable = true

[Remote Rewrite]
#è®¢é˜…é‡å†™ å»å¹¿å‘Š by eHpo
# æ ¼å¼ï¼šè®¢é˜…urlï¼Œåˆ«å(å¯é€‰)
https://raw.githubusercontent.com/eHpo1/Rules/master/Loon/Rewrite.conf,eHpo
https://raw.githubusercontent.com/nzw9314/Loon/master/Q-Search_All_in_one.conf,Q-Search_All_in_one
[Script]
# æœ¬åœ°è„šæœ¬
enable = true

[Remote Script]
# è¿œç¨‹è„šæœ¬
https://raw.githubusercontent.com/nzw9314/Loon/master/Task.conf,ç­¾åˆ°
https://raw.githubusercontent.com/nzw9314/Loon/master/Script.conf,è„šæœ¬
https://raw.githubusercontent.com/nzw9314/Loon/master/Cookie.conf,Cookie

[MITM]
enable = true
hostname = *.googlevideo.com
skip-server-cert-verify = true
ca-p12 = MIIJrgIBAzCCCXgGCSqGSIb3DQEHAaCCCWkEggllMIIJYTCCA/8GCSqGSIb3DQEHBqCCA/AwggPsAgEAMIID5QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIYl/myyqpUtwCAggAgIIDuMYEzEUgSxIUScp1vSSooV2iePmy4Q7YP8cfnhaatGNnX+CC9/rDdPgDuz7k1D/7hYdaOsTKpXU9aUAxHvg9SLAWFm5dL4g/9MVk7Id8qCPMYbO2H+lQTChEN8iTpWdq+qlAC8VpqY1TTXhQTkCKF3cT+S68xZUMFDuX95INBUswjN+imGIYVKFBp4s0K7UDFpF0BMUD5HwR9U/QFsZ+ScCaNj/Y1p95LWPllUkeeb67uTOeXc55yEM+O8W/SGjJhgjdnvPgetCfLMc6RWREK0SNAGMzHibuvHHHm0fIBg5zwE+DjDdefwYMUghpQVl+0gSeASjsvP9mSgtm9+horQCw/ef0a3FxcKsmTzSE6o4dx37fEckEouYN/Ni+OWnKWb6eXeaL6yVD4gLDmEwV8lmgBG4OjYcdY9jeIBFkDzbG70eUvmj6/1olUtnOnkGY5ZMvCGhVr8K4ZJ80xuykgxgPI/5enNZZiS9cAuk85xAN+XeDvmQdIHF9TxMRyLGJyWUkczjV3DSPkqZ2hMFJRuOF5zbhZlCcJgkEdCYbb4sebYnGKOEVnfceFVK1yv33Hp+BcQDmqEm+gssrtNhJGCWtqTjT28WeGxGgAWOaY2e+isVJG6TvU1D+tHCl09WyLKM671a63jY6QvpWwRpSMkbcrGEMhQRo2IMrxhwkia9vkk+eDYRt4jJcG8gRAWB0crXuYMM/t0gxDKTiVF7aS0XEHWMkH7ATWFI/+Yta4dsVLAOACnTCarD80RH/xV5JK1KiAn5pSzy13fRwvYcHAluJ/7JHphVUtNYroNgfzdt5n65B7qD5PU4ykhVMfflZXom17VGwUqf750kx0fowU23XCUyWoifoGBbkR9mgGHBqZyMZHv+Z9iWPmpqJcfjL9UBX91Ulzg74IQocvNTHMVu3cLXx63OiQ6k4+FYZcvTiJyYpu7N36I/nLz61L3D2d8LaYLHAcvnsClfC6QRVVAU/wvQnhp2/oPh/l19KBX7QUnBKPU1oFLEV8y1G87IbN/LDJ0SUroS/McCojANgutTpKQJT+5jlid+GxZkEi4CXlTAUfu6/lioLdJugycPEKHu49zAmbDw8lUy5QRUbyjWrZk8tLu2bKzaxg5A21N9N/zKt9uXmcN5J/O1L8WIcAIXDytAmkyw7ez45EF631i6k2uJeuIxtBwRfwDyuw4FwKrsqw197FoqsvsMb68Tak2vVtzgs/rSQ1PL3acsLQ0CBZ9/Do1WxAb8azc4ko36JE7e0xtM43qswggVaBgkqhkiG9w0BBwGgggVLBIIFRzCCBUMwggU/BgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQI3rZrdI9fPuMCAggABIIEyGZyUi/orJ8LMBdjZFQaCNXECddtwPuKPg+QxAzpxC0/VSgdtHsOR/v8koAJgddmGJUDwLXGVcuasJ7YlhdIKpnvSzNBB7qjJoQBQ5dMsXVfcJaRwbhjMExjZyvUjCKH21lJ7yaxGQORtmIXTpx0FPQUprJtghF/C2ejA9QSW+SCjYY64dkvUovvXMDaddKWq+i0lOGKi0hvCjGiLobIovBpSfjX1EYTK5pmpBtWKro5Wnm/Q5r/OBU2+PyzlFCZdMdov7bIcUwnz4D1Oypn6woQol8N9AqgQL52pMweL8k0fK8YH3eChE5EP0JNc1X0vRTHhKiAB0Su5vjSVa5QU4ZBTCdNdwM7rr2NJMzMjF8g4y7fXMTVXdPUi1QeYihOqmcU2i0pmrk4zPeobGfzLIcgRSLf9qeP2r9Gw3yt3rjJMHgbx6QvBZ+5GZ8/iooQTbLjUj83QfdGeidkD+Auba9f8cPDiurDF+Pjt2FotaT3Vqx38qlaprBdlk7H1yVZtY2G5Y5pquiyPK/C+QwrXYWEocsJIAvAb3xhXalqkUs6ZmKTVQqlpUR0L/ogRmeJ0OxHYKbqy4Rg2eIcHogPEK2Xa2iiPFmG6AbWUnE8mmH5PunCPGuhcOxFYZAkpf96//c0J9ry52pcvR15ZIvmZdSLrhjD4pD+CElUKFS6izafXSyFQpjNuQI2aCnMNS/AFSe3kH6naARoOUnXFC7Wz+e69nOKs6G84/gV3xD4klk5vCza32e55MtUD9SX09+q9XItarBeBYCn3XCZk1sZADmg8gHxZzgEj3mA7slqsRnx7E80lz1UlHU4FSLkeMEU2u9/K1QA6VZzFfFRXtitZuam2Di98zCyftyb0D0DwlywSab/ww7VrROnBq3sozc7uo7eEiT8Jx9qd2kGNF+r9KI6QePBtATJzsgCNoPHNTdA7DNX4opD0bNsRtFHQLW3b9k1PeeAix1agcrqsDVV2PsWn9Qae9vY4zqwkNY+hjlmt2CRPG/5pX8COVn+dzqGHTksFg/NgVZsAj8NK4ZGf+QSRxSUo/5sYbu61Pj6TpyEIjOEPM+ylXdhziKhDTfw4GkrmTjlrQQ9T+7pqC86nYS8HH9ZcET+SecZK8kMPe7pwbzwHPWsl+OqHTP01KvEAogOL8fAZ7LsbaHlPoLHkHDQzxeep6ZKDnoCphjsf4oqSlcQzNh383mAr0YTPY8SaVV5G6Hh9mCHQqKWWmXhNd8rN/kqZn0H7KvfMJW2BGVWgCvYaE5m5sodhHYjSMGzgauV7O9DL3H+Az2Ztz0K2hj11xsz/C7nRVNOgV02rDvIEHw0asBPq2gYPC4OG/HutK+etT87z+tLftGO9V5+TMcIc4JKaNVOUg814DP59yo/WptH346rHwY7AqvgmEi6LJ1LLP9W6+HH1k3Fk6WEpOtDJS3YqV4EjswXGCtLXu6y/IvqLkyvT7NIZi/BYFf39xwJDvD5SbLM2jhCShG/HsD0/4qfqeGA/x4LLaM9Lyl091XeKWtY9XpP9nZzfgOJkk2rsBH29jS5d8lLkz+GhdzrROPIgHn+yaSsp8vIwr8L9h27+6/95kbUiQugOWEWdO/ZO+X/iyhThallmiNbJP+Qv3abUJgzcTE+MBcGCSqGSIb3DQEJFDEKHggAZQBIAHAAbzAjBgkqhkiG9w0BCRUxFgQU5gr9fNKSpq6pZ3g5Hca/uXOuY+cwLTAhMAkGBSsOAwIaBQAEFKXWG0IDj30Q2VfVGNWcVJ8iipuZBAgHvSM3D+pSUA==
ca-passphrase = eHpo